### ISSUE TITLE
Problems with the evaluation part 

### ISSUE THREAD

**Issue by shahaamirbader** [liuzuxin/OSRL#13]
Hi, 

I am trying to run the evaluation using the commands provided on the readme. Seems like there is no config file in the checkpoints folder, just the model.pt and model_best.pt. Here is the list of all files in the directory

![image](https://github.com/liuzuxin/OSRL/assets/78397774/6484bc81-8c59-4ca5-8b12-3aef28198719)

When I try to run the Eval_cdt.py I get the following error where it says that config file location is not a directory. What am I doing wrong here? 

The path to my model and best_models are "/home/xubuntu/Desktop/homelocal/3rd Year/DT_RL/OSRL/logs/OfflineCarPush1Gymnasium-v0-cost-5/CDT_cost5-eea0/CDT_cost5-eea0/checkpoint/mode.pt "

I even tried to give the path argument as you have mentioned in the command in your readme but still the same issue. See the below screenshot please. 

![image](https://github.com/liuzuxin/OSRL/assets/78397774/4b7c9737-af5d-4391-a9c6-62be5d3845ec)
In this screenshot I entered the model path inside the eval_cdt.py file and hence path argument is not used here 

![image](https://github.com/liuzuxin/OSRL/assets/78397774/738047bb-6c26-4cb2-bee2-b857ff25224a)

**Comment by Ja4822** [comment]
@shahaamirbader Hi, there should be a `config.yaml` in this directory: `/home/xubuntu/Desktop/homelocal/3rd Year/DT_RL/OSRL/logs/OfflineCarPush1Gymnasium-v0-cost-5/CDT_cost5-eea0/CDT_cost5-eea0/` if you didn't comment out this [line](https://github.com/liuzuxin/OSRL/blob/main/examples/train/train_cdt.py#L44). 

To evaluate the trained model, run this command: 
```
cd <directory>/OSRL
python example/eval/eval_cdt.py --path logs/OfflineCarPush1Gymnasium-v0-cost-5/CDT_cost5-eea0/CDT_cost5-eea0/
```
you may also need to comment out these [two lines](https://github.com/liuzuxin/OSRL/blob/main/examples/eval/eval_cdt.py#L36-L37). Sorry for the inconvenience, we will fix these bugs regarding to gym in our future updates.

**Comment by shahaamirbader** [comment]
Thanks. This helps. I was finally able to run the evaluation on the trained model. Here is the output. Can you help me understand how can this result be checked against the benchmarks results that you show in the paper? 

![image](https://github.com/liuzuxin/OSRL/assets/78397774/85ed135c-8434-41d4-b5db-db49ab5eee80)

**Comment by liuzuxin** [comment]
Which paper's results are you referring to? The datasets we released are for the [benchmark paper](https://arxiv.org/abs/2306.09303), where we average the results w.r.t three seeds and three different target cost thresholds. Regarding the original datasets used in the CDT paper, please check this [issue](https://github.com/liuzuxin/OSRL/issues/9#issuecomment-1685668344).

**Comment by shahaamirbader** [comment]
Thanks, I was referring to the CDT paper, table 1. I wanted to replicate the results shown in table 1 for the dataset. Let me have a deeper look at the issue you shared. Closing it for now.
