### ISSUE TITLE
DT-Cost file missing in examples 

### ISSUE THREAD

**Issue by shahaamirbader** [liuzuxin/OSRL#14]
Hi,

I see that one of your baseline method is a simple DT-Cost. But I am unable to find the files in examples folder for DT-Cost. Can you kindly share those files for training.

Thanks

**Comment by liuzuxin** [comment]
You can simply enable DT-Cost mode by using our CDT implementation and  set the following parameters:
```
# disable data augmentation
augment_percent = 0
# disable stochastic policy head
stochastic = False
```

**Comment by shahaamirbader** [comment]
Perfect, thanks. Can you explain how this will make it a simple DT+Cost based transformer.

**Comment by liuzuxin** [comment]
You are welcome. By removing data augmentation, the data side has no much additional operations, and by removing the stochastic policy head, the model uses the same deterministic head as DT (also without entropy regularization), so it is essentially just performing DT with an additional target cost token.

**Comment by shahaamirbader** [comment]
perfect thanks. This helps.
