### ISSUE TITLE
How can I use this on Atari dataset?

### ISSUE THREAD

**Issue by shahaamirbader** [liuzuxin/OSRL#15]
Hi,

I would like this model to take visual observations as inputs (for example from Atari dataset) rather than trajectories. Is there a way I could do that? 

Thanks

**Comment by liuzuxin** [comment]
I think you could use a vision encoder such as resnet or vit to preprocess the Atari images, and then send the encoded hidden states to the CDT model.

**Comment by shahaamirbader** [comment]
Thanks. Closing this.
