### ISSUE TITLE
Using CDT for Multi-Agent Reinforcement Learning

### ISSUE THREAD

**Issue by shahaamirbader** [liuzuxin/OSRL#16]
Hi, 

I was wondering if this framework can be used for a Multi Agent RL problem. 

if not, can you list the limitations that would be stop this model from being used in a Multi Agent RL problem. 
If yes, can you explain the additional steps that will be required for me to use this model in a Multi Agent RL problem. 

Thanks

**Comment by liuzuxin** [comment]
Hi, I am not quite familiar with offline multi-agent RL, but I think the decision transformer framework can definitely be applied. I did some search and found the following two papers which might be helpful to you: https://arxiv.org/abs/2112.02845, https://arxiv.org/abs/2205.14953

**Comment by shahaamirbader** [comment]
Thanks will look into those papers. Appreciate it.
