### ISSUE TITLE
The output of the training result is empty

### ISSUE THREAD

**Issue by Yang6852** [liuzuxin/OSRL#23]
I ran the command`python examples/train/train_bcql.py --task OfflineCarCircle-v0` as illustrated in the example.However, i found the output of the training result is empty.I looked at the web of wandb but it didn't generate any icons, just some empty folders.And `logs/OfflineCarCircle-v0-cost-10/BCQL-3d74/BCQL-3d74/progress.txt` is also empty.There mush be something wrong,but i don't know why.I‘m looking forward to your help.
![image](https://github.com/liuzuxin/OSRL/assets/66681868/eb8a8086-2ee5-4e08-9da2-45beccda8b60)
![image](https://github.com/liuzuxin/OSRL/assets/66681868/cf901e31-1e1d-422c-a5f8-c90ace32a398)
![image](https://github.com/liuzuxin/OSRL/assets/66681868/78728fdd-0ef6-42bc-9b20-9945f7b8340d)
![image](https://github.com/liuzuxin/OSRL/assets/66681868/eecc8d17-4397-4419-b525-31bbc24c55e2)

**Comment by liuzuxin** [comment]
This issue seems to have been addressed with the latest version. Could you have a try?

**Comment by Yang6852** [comment]
来信已收到

**Comment by Eternity-Wang** [comment]
Hi, I also meet the same problem when executing that `train_bcql.py` file, could you please tell me how you solved it in the end?

**Comment by Yang6852** [comment]
来信已收到
