### ISSUE TITLE
Can not train MetaDrive datasets

### ISSUE THREAD

**Issue by Chenrf1121** [liuzuxin/OSRL#26]
I would like to train algorithms on metadrive env (OfflineMetadrive-harddense-v0),
the traceback is: 
`raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment ''OfflineMetadrive-harddense'' doesn't exist.`
How to address it?
Thanks.

<img width="1252" alt="image" src="https://github.com/user-attachments/assets/ea33f77a-e52d-4883-ac34-311eb8e13c60">

**Comment by liuzuxin** [comment]
Did you follow the instruction [here](https://github.com/liuzuxin/DSRL#install-from-pypi) to install the metadrive environment?

**Comment by Chenrf1121** [comment]
Thanks, I changed the code, so received the error.
