### ISSUE TITLE
missing CORL citation

### ISSUE THREAD

**Issue by Howuhh** [liuzuxin/OSRL#3]
Hi! Great work, surely, safety is a very important topic in offline RL. However, we are a little bit puzzled by the complete lack of citations for the [CORL](https://github.com/tinkoff-ai/CORL) library, considering that:

1. CORL is a library that is closer in spirit and implementation to OSRL, yet the article cites only d3rlpy. And more broadly, CORL is used in many papers and projects in offline RL, so we feel that a review of related work without mention of CORL is incomplete.
2. CORL seems to have had a lot of influence on the design and code of this library, as one can find comments and code parts taken directly from CORL. For example, code on OSRL [[1](https://github.com/liuzuxin/OSRL/blob/3e586b78535fca66be73b6ab380aceb190257161/osrl/algorithms/cdt.py#L219), [2](https://github.com/liuzuxin/OSRL/blob/3e586b78535fca66be73b6ab380aceb190257161/osrl/algorithms/cdt.py#L481)] and exactly the same code in CORL [[1](https://github.com/tinkoff-ai/CORL/blob/6c5488fd8de775d3808cec131f3f69d9ffd9c8ed/algorithms/offline/dt.py#L341), [2](https://github.com/tinkoff-ai/CORL/blob/6c5488fd8de775d3808cec131f3f69d9ffd9c8ed/algorithms/offline/dt.py#L379)].

We would like to remind you that CORL is licensed under the Apache License. If you borrow code like this, you *should* give credit to the source. Also, such misconduct could actually be a significant violation of the NeurIPS Datasets and Benchmarks Track rules.
 
 Thus, we would highly appreciate if you credited CORL both in the code and publication. Thanks in advance!

**Comment by liuzuxin** [comment]
Hi @Howuhh , thanks for pointing this out! We would like to express our sincerest apologies for the oversight. We indeed got a lot of inspiration from the amazing CORL library, both from the framework design and code implementation side. It was my mistake not to check the references and license carefully before releasing the code. We will add citations both in the paper and the code and the readme file. Thanks again for bringing this up at this early stage!
